[tools]
python = "3.14.0"

[env]
_.python.venv = { path = ".venv", create = true }
QMK_HOME = "{{config_root}}/qmk/qmk_firmware"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[tasks.draw]
description = "Generate keymap drawings"
alias = "d"
run = "./scripts/draw.sh"
